@if exist %~dp0\cmake-tools-kits.auto-scanned.json exit /B 1
@call %~dp0\00-make-help.bat
@call %~dp0\01-copy_kits_config_to_here.bat
@call %~dp0\02-replace-autogenerated-kit-names.bat > %~dp0\replace.log
@rem call %~dp0\02a-meld.bat